name: release
on:
  push:
    tags: ["v*"]
jobs:
  artifacts:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - run: go build -o vantrilex ./cmd/vantrilex/
      - uses: actions/upload-artifact@v4
        with:
          name: vantrilex-${{ matrix.os }}
          path: vantrilex*
